apiVersion: apps/v1
kind: Deployment
metadata:
  name: TasksProcessor
spec:
  selector:
    matchLabels:
      app: TasksProcessor
  template:
    metadata:
      labels:
        app: TasksProcessor
    spec:
      containers:
      - name: tasksProcessor 
      image: shaunsimsimtech/tasksprocessor:1.0.0
      resources:
          limits: 
            memory: "1024Mi"
            cpu: "500m"
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: Tasks_service
  annotations:
    konghq.com/plugins: 12-per-min
spec:
  type: NodePort
  selector:
    app: Tasks_service
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32500